Repository virtualCrypto-discord/virtualCrypto2, pull requests merged in 2021-02, with the labels that each got.

#137 remove documents
  assets/elm/src/Docs.elm
  assets/elm/src/Document.elm
  assets/js/docs.js
  docs/about.md
  docs/commands.md
  docs/parsed/.keep
  lib/mix/tasks/docs.ex
  lib/virtualCrypto/markdown_parser.ex
  lib/virtualCrypto_web/controllers/document_controller.ex
  lib/virtualCrypto_web/router.ex
  lib/virtualCrypto_web/templates/document/docs.html.eex
Labels: documentation

#146 update readme and example
  README.md
  config/dev.exs.example
Labels: documentation

#163 set lower limit of pool amount
  lib/virtualCrypto/money/interface.ex
  lib/virtualCrypto/money/internal_action.ex
Labels: Core, bug

#164 fix site_url
  lib/virtualCrypto_web/views/api/interactions_view.ex
Labels: Bot, bug

#165 fix show nothing when invalid amount supplied to create command
  lib/virtualCrypto/money/interface.ex
  lib/virtualCrypto/money/internal_action.ex
  lib/virtualCrypto_web/command_handler.ex
  lib/virtualCrypto_web/views/api/interactions_view/create.ex
Labels: Bot, bug

#166 fix showing no error when using the "give" command with the invalid amount
  lib/virtualCrypto/money/interface.ex
  lib/virtualCrypto/money/internal_action.ex
  lib/virtualCrypto_web/views/api/interactions_view/give.ex
Labels: Bot, bug

#155 display pool amount at info
  lib/virtualCrypto_web/views/api/interactions_view/info.ex
Labels: Bot, enhancement

#170 make decline invalid amount claim
  lib/virtualCrypto/money/interface.ex
  lib/virtualCrypto/money/internal_action.ex
  lib/virtualCrypto_web/command_handler.ex
  lib/virtualCrypto_web/views/api/interactions_view/claim.ex
Labels: Bot, bug
